# Generated by Django 2.2.4 on 2020-05-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='value',
            field=models.DateField(max_length=255),
        ),
    ]
