# Generated by Django 2.2.4 on 2020-04-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_author_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='booksWritten',
        ),
    ]
