# Generated by Django 2.2.4 on 2020-04-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(null='old dojo'),
            preserve_default='old dojo',
        ),
    ]
